name: dinamica_landing_page
description: Landing page of Dinamica Pay.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  responsive_framework: ^0.2.0
  url_launcher: ^6.0.20
  video_player: ^2.2.18
  url_strategy: ^0.2.0
  scroll_pos: ^0.3.0
  flutter_native_splash: ^2.2.16
  flutter_custom_clippers: ^2.1.0
  animate_do: ^3.0.2
  email_validator: ^2.0.1
  http: ^0.13.4
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/dinamica/dinamica-center-red.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/videos/
    - assets/images/
    - assets/images/parallax/
    - assets/images/dinamica/
    - assets/images/available-buttons/

 