name: dinamica_landing_page
description: Landing page of Dinamica Pay.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Responsive
  responsive_framework: ^0.2.0
  
  # Open link
  url_launcher: ^6.0.20
  
  # Design
  flutter_custom_clippers: ^2.1.0
  
  # Splash screen
  flutter_native_splash: ^2.2.16
  
  # Request
  http: ^0.13.4
  
  # Delete "#"
  url_strategy: ^0.2.0
  
  # Animations
  animate_do: ^3.0.2
  scroll_pos: ^0.3.0

  # Validations
  email_validator: ^2.0.1
  string_validator: ^0.3.0

  # State Management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # Freezed
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0

  # Table
  responsive_table: ^0.2.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Freezed
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/dinamica/dinamica-center-red.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/parallax/
    - assets/images/dinamica/
    - assets/images/available-buttons/

 