String tituloCGL =
    "Condiciones Generales del otorgamiento de Préstamos por parte de DINÁMICA de Credina S.A.";

String a0CuerpoCGL =
    "Este documento establece los términos y condiciones generales (las “Condiciones Generales”) de la relación jurídica que se celebra entre Credina S.A. CUIT N° 30-71230182-8, con domicilio en Tucumán n°189 de la ciudad de Santiago del Estero (CP 4200) de Santiago del Estero (en adelante, “DINÁMICA”) y un Usuario registrado en las plataformas brindadas por  DINÁMICA en ";

String a1CuerpoCGL = "www.midinamica.com.ar";

String a2CuerpoCGL =
    " y/o en las aplicaciones de dispositivos móviles de titularidad de DINÁMICA (en adelante, las “Plataformas”), al que DINÁMICA le ofrezca y/o le otorgue un préstamo de dinero (el “Usuario Tomador”) en base a sus políticas crediticias, comerciales y de riesgo. \n\nEl préstamo para consumo ofrecido u otorgado por DINÁMICA al Usuario Tomador (el “Préstamo”) está sujeto a estas Condiciones Generales y a los términos y condiciones particulares relativos a cada Préstamo particular (las “Condiciones Particulares”).\n\nLas Condiciones Particulares son las siguientes:";

String bCuerpoCGL =
    "• El importe del Préstamo en moneda de curso legal en Argentina (el “Importe del Préstamo”);\n• El régimen de reembolso del Préstamo (el “Régimen de Reembolso”), que incluye: las cuotas (las “Cuotas”), la cantidad de Cuotas, su importe, forma de pago y el plazo de vencimiento de cada Cuota (el “Vencimiento”);\n• Los intereses compensatorios y los punitorios (los “Intereses Compensatorios” y los “Intereses Punitorios”, respectivamente); y\n• Los cargos, comisiones y gastos que sean de aplicación (los “Cargos”).";

String cCuerpoCGL =
    "Las Condiciones Particulares se encuentran establecidas en la oferta de préstamo que DINÁMICA emite y dirige al Usuario Tomador (la “Oferta de Préstamo”).\n\nEl Usuario Tomador reconoce que la solicitud, aceptación y obtención del Préstamo implica la aceptación de estas Condiciones Generales y demás documentos incorporados a ellas, así como de las Condiciones Particulares (en adelante, en conjunto, denominados el “Contrato”). El Usuario Tomador acepta que sus derechos y obligaciones en relación con el Préstamo se rijan por el Contrato.";

String ofertaAceptacionPrestamoTituloCGL =
    "1. Oferta y aceptación del Préstamo";

String aOfertaAceptacionPrestamoCuerpoCGL =
    "La Oferta de Préstamo es emitida por DINÁMICA y dirigida al Usuario Tomador a través de distintos canales online. Sólo es válida para el Usuario destinatario de la Oferta de Préstamo.\n\nLa Oferta de Préstamo estará vigente durante el plazo indicado en dicha Oferta de Préstamo. Si durante ese plazo, DINÁMICA tomara conocimiento de algún cambio en la situación del Usuario Tomador que volviera incierta la restitución del Préstamo y/o si existieran razones que tornan incierta la identidad y/o legitimidad del Usuario solicitante del Préstamo, DINÁMICA podrá dejar sin efecto la Oferta de Préstamo y/o negarse a entregar el Importe del Préstamo, sin necesidad de indicar las razones y sin penalidad alguna.\n\nEl Usuario Tomador que desee solicitar un Préstamo lo utilizará para la adquisición de bienes y/o servicios ofrecidos a través de las Plataformas y/u ofrecidos por terceros que procesen sus pagos a través de DINÁMICA, debiendo:";

String bOfertaAceptacionPrestamoCuerpoCGL =
    "1) Seleccionar “DINÁMICA Crédito” como medio de pago.\n2) Aceptar las Condiciones Generales (y demás documentos incorporados a ellas) y las Condiciones Particulares del Préstamo, seleccionando la opción “Confirmar” (u opción similar que en un futuro la reemplace), mediante la cual se confirma la concreción de la transacción de compra del bien, producto o servicio que se pretende adquirir y abonar, y se confirma el otorgamiento del Préstamo aceptando el Usuario Tomador expresamente estas Condiciones Generales y las Condiciones Particulares del Préstamo (la “Aceptación”).";

String cOfertaAceptacionPrestamoCuerpoCGL =
    "A los fines de la Aceptación, el Usuario Tomador deberá acceder a cualquiera de las Plataformas mediante el ingreso de su dirección de e-mail y contraseña de ingreso personal. El Usuario Tomador es el único y exclusivo responsable por todas las operaciones efectuadas con su dirección de e-mail y contraseña de ingreso en las Plataformas.";

String prestamoTituloCGL = "2. Préstamo";

String prestamoCuerpoCGL =
    "El Préstamo será aplicado por el Usuario Tomador para el pago del precio de las compras de bienes, productos o servicios efectuadas a través de cualquiera de las Plataformas.\n\nEl Importe del Préstamo será el que se establece en las Condiciones Particulares.\n\nEl desembolso y reembolso del Préstamo se rige por las condiciones que se establecen a continuación.";

String desembolsoPrestamoTituloCGL = "3. Desembolso del Préstamo";

String desembolsoPrestamoCuerpoCGL =
    "Una vez perfeccionado el Préstamo en virtud de la Aceptación por parte del Usuario Tomador, DINÁMICA procederá a desembolsar el Importe del Préstamo en la Cuenta DINÁMICA del vendedor o vendedores de los bienes o servicios adquiridos por el Usuario Tomador (el “Usuario Vendedor”), o bien en la Cuenta DINÁMICA del Usuario Tomador en caso que corresponda. A tal efecto, el Usuario Tomador instruye expresamente a DINÁMICA, otorgándole mandato suficiente e irrevocable, a fin de que el Importe del Préstamo desembolsado sea acreditado directamente en la cuenta del Usuario Vendedor.\n\nEl Préstamo se considera otorgado el día en que se perfecciona en virtud de la Aceptación.";

String interesesCompensatoriosTituloCGL = "4. Intereses Compensatorios";

String interesesCompensatoriosCuerpoCGL =
    "El Préstamo devengará Intereses Compensatorios calculados de acuerdo a la tasa fija nominal anual (“TNA”) que se establece en las Condiciones Particulares sobre el Importe del Préstamo. Los Intereses Compensatorios se encuentran alcanzados por el impuesto al valor agregado a cargo del Usuario Tomador.\n\nLa tasa efectiva anual (“TEA”) y el costo financiero total nominal anual (“CFTNA”) se exponen en las Condiciones Particulares.\n\nSistema de amortización: sistema francés.";

String reembolsoTituloCGL = "5. Reembolso";

String reembolsoCuerpoCGL =
    "El Usuario Tomador deberá reembolsar el Préstamo a DINÁMICA de acuerdo con el Régimen de Reembolso establecido en las Condiciones Particulares. El reembolso se realizará en moneda de curso legal en Argentina.\n\nLas Cuotas serán iguales, mensuales y consecutivas, por el importe que se disponga en las Condiciones Particulares. El importe de las Cuotas comprende los Intereses Compensatorios que el Usuario Tomador debe pagar a DINÁMICA en cada Vencimiento, y el impuesto al valor agregado.\n\nEl Usuario Tomador deberá seleccionar el medio de pago que desee utilizar para pagar cada Cuota, en base a los medios de pago disponibles indicados en su Cuenta DINÁMICA.\n\nAsimismo, el reembolso podrá realizarse mediante el débito del  importe de las Cuotas de los Fondos disponibles en la Cuenta DINÁMICA del Usuario Tomador o en otras Cuentas DINÁMICA que sean operadas por el Usuario Tomador. De la misma manera, DINÁMICA podrá debitar los importes correspondientes de las Cuotas de las cuentas bancarias de su titularidad que el Usuario Tomador tenga registradas en las Plataformas.\n\nA estos efectos, el Usuario Tomador autoriza expresa e irrevocablemente a DINÁMICA a debitar de su Cuenta DINAMICA y/o de las Cuentas DINÁMICA relacionadas y/o de las cuentas bancarias de su titularidad registradas por el Usuario Tomador en las Plataformas, el importe de las Cuotas a su vencimiento conforme lo establecido precedentemente, incluyendo los Intereses Compensatorios, más el impuesto al valor agregado y cualesquiera otros Cargos, conforme lo establecido precedentemente, como así también cualquiera suma adeudada bajo el Préstamo (incluyendo, sin limitación, el Importe del Préstamo, los Intereses Compensatorios, los Intereses Punitorios, el impuesto al valor agregado, y cualesquiera otros Cargos), en cualquier momento mientras persista el estado de mora. El Usuario Tomador deberá pagar a DINÁMICA cualesquiera otros Cargos que hayan sido aceptados por el Usuario Tomador en virtud del Contrato.";

String cancelacionAnticipadaTituloCGL = "6. Cancelación Anticipada";

String cancelacionAnticipadaCuerpoCGL =
    "El Usuario Tomador podrá reembolsar voluntariamente y en forma anticipada el Importe del Préstamo, en forma total o parcial, por los mismos medios y modalidad de reembolso previstos en la Cláusula 5 precedente, debiendo abonar en esta oportunidad, la totalidad de los Intereses Compensatorios, Intereses Punitorios, Cargos y otras sumas no abonadas bajo el Contrato y devengadas hasta la fecha de dicha precancelación.";

String vigenciaTituloCGL = "7. Vigencia";

String vigenciaCuerpoCGL =
    "El Contrato estará vigente hasta el cumplimiento total de las obligaciones a cargo del Usuario Tomador y se entenderá cumplido cuando el Usuario Tomador haya efectuado el reembolso total del Préstamo, y haya pagado la totalidad de cualesquiera Intereses Compensatorios, Intereses Punitorios, Cargos y otras sumas adeudadas a DINÁMICA bajo el Contrato.";

String moraTituloCGL = "8. Mora";

String moraCuerpoCGL =
    "La mora se producirá de pleno derecho en forma automática al Vencimiento de cualquier Cuota, si ésta no hubiera sido cancelada a esa fecha en su totalidad. En caso de mora, el Usuario Tomador deberá abonar a DINÁMICA un Interés Punitorio cuya tasa será por hasta el equivalente de dos veces la Tasa Nominal Anual (TNA) establecida en las Condiciones Particulares para los intereses compensatorios. Los Intereses Punitorios se devengarán sobre saldos impagos desde la fecha de mora y hasta el efectivo pago. Los Intereses Punitorios se encuentran alcanzados por el impuesto al valor agregado a cargo del Usuario Tomador. Cualquier suma que DINÁMICA debite de la Cuenta DINÁMICA del Usuario Tomador o que DINÁMICA perciba del Usuario Tomador que se encuentre en mora, será imputada a la cancelación de las sumas adeudadas por los diferentes conceptos, en el siguiente orden: en primer lugar, al pago de los eventuales Cargos, incluyendo los costos impositivos que pudieran corresponder; en segundo lugar, a la cancelación de los Intereses Punitorios; en tercer lugar, a la cancelación de los Intereses Compensatorios; y en cuarto lugar, al pago del capital del Préstamo.\n\nLos conceptos adeudados por el Usuario Tomador a raíz de la mora sólo podrán considerarse extinguidos mediante un recibo de pago emitido por DINÁMICA, con referencia explícita a dichos conceptos, expresado en la sección “Movimientos” de la Cuenta de DINÁMICA del Usuario Tomador. En tal sentido, DINÁMICA hace expresa reserva de los créditos a su favor que se originen en dichos conceptos.\n\nDINÁMICA podrá percibir del Usuario Tomador  honorarios por acciones y gestión de cobranza, en aquellos casos en que el Usuario Tomador esté en mora y dicha mora hubiera generado la necesidad de DINÁMICA de realizar, por si o por terceros, acciones de gestión de cobranza del Préstamo adeudado.";

String resolucionEventosIncumplimientosTituloCGL =
    "9. Resolución – Eventos de Incumplimiento";

String aResolucionEventosIncumplimientosCuerpoCGL =
    "En cualquiera de los casos que se establecen a continuación, el Préstamo podrá ser declarado de plazo vencido por parte de DINÁMICA sin necesidad de interpelación judicial o extrajudicial alguna (los “Supuestos de Incumplimiento”). En tales casos, el Préstamo, los Intereses Compensatorios, los Intereses Punitorios, los Cargos y costos impositivos, y cualesquiera otras sumas debidas a DINÁMICA bajo el Contrato, se considerarán íntegramente debidos y exigibles acelerándose los plazos y pudiendo DINÁMICA, en consecuencia, exigir el pago íntegro del mismos:";

String bResolucionEventosIncumplimientosCuerpoCGL =
    "• En caso de cesión por parte del Usuario Tomador de sus obligaciones y derechos bajo el Contrato y/o su posición contractual bajo el Contrato.\n• En caso de incumplimiento del Usuario Tomador en el reembolso de al menos dos (2) Cuotas consecutivas a su Vencimiento.\n• Si el Usuario Tomador solicitare su concurso preventivo o quiebra, o si proviniendo de un tercero el pedido de quiebra, el Usuario Tomador no levantara dicho pedido de quiebra dentro de los 5 días hábiles judiciales, o si el Usuario Tomador ordenara o aprobara una medida que efectivice una resolución de liquidación o disolución del Usuario Tomador.\n• Si el Usuario Tomador ejecutara conductas que, razonablemente, hicieran previsible el incumplimiento por parte del Usuario Tomador de cualquiera de sus obligaciones bajo estas Condiciones Generales y/o bajo las Condiciones Particulares.\n• Si el Usuario Tomador incumpliera total o parcialmente y/o se encontrare en mora en el cumplimiento de cualquier otra obligación asumida frente a DINÁMICA (incluyendo, pero no limitado a, mora en cualquier otro producto crediticio vigente del Usuario Tomador).\n• Cualquier evento o supuesto de fraude asociado al Usuario Tomador por cualquiera de los productos contratados y/o adquiridos con DINÁMICA; o si el Usuario Tomador hubiera iniciado un reclamo o acción legal o administrativa contra DINÁMICA por cuenta propia y/o por cuenta de terceros y/o si hubiera sospechas razonables de que el Usuario Tomador opera a través de una Cuenta DINÁMICA Relacionada.\n• Si el Usuario Tomador hubiera incurrido en falsedad, inexactitud u omisión material, con culpa o dolo, respecto de la información provista a DINÁMICA.\n• Cualquier supuesto en que el Usuario Tomador hubiera solicitado el cierre de su Cuenta DINÁMICA mientras continúe vigente el Préstamo, debiendo permanecer dicha Cuenta abierta hasta la total cancelación todos los montos adeudados bajo el Contrato.";

String cResolucionEventosIncumplimientosCuerpoCGL =
    "DINÁMICA se reserva el derecho de suspender temporal o definitivamente la Cuenta DINÁMICA de titularidad del Usuario Tomador, sin necesidad de notificación previa, ante la ocurrencia de cualquiera de los Supuestos de Incumplimiento referidos precedentemente.";

String responsabilidadTituloCGL = "10. Responsabilidad";

String responsabilidadCuerpoCGL =
    "El Usuario Tomador deberá indemnizar a DINÁMICA por todos los daños y perjuicios ocasionados como resultado de la provisión de información falsa o del incumplimiento de cualquiera de las obligaciones del Usuario Tomador previstas en este Contrato, incluyendo todos los gastos y honorarios que origine, en caso de mora, su cobranza judicial o extrajudicial.\n\nEl Usuario Tomador desde ya declara conocer, aceptar y asumir los eventuales riesgos derivados de este tipo de modalidad contractual, ya sea riesgos de que terceros no autorizados accedan a la información correspondiente a su Cuenta, riesgos derivados de la indisponibilidad de las Plataformas debido a dificultades técnicas o fallas de Internet en los links u otras herramientas que afecten el proceso de adquisición de los bienes y/o servicios solicitados o por cualquier otra circunstancia ajena a DINÁMICA.\n\nDINÁMICA no garantiza el acceso y uso continuado o ininterrumpido de las Plataformas, que pueden eventualmente no estar disponibles debido a dificultades técnicas o fallas de Internet o por cualquier otra circunstancia, incluso ajena a DINÁMICA. Los Usuarios no podrán imputarle responsabilidad alguna a DINÁMICA, ni exigir resarcimiento alguno, en virtud de perjuicios resultantes de las mencionadas dificultades, incluso en el caso que dichas fallas afecten los montos que deban ser acreditados en o debitados de su Cuenta DINÁMICA por motivo del Préstamo.\n\nDINÁMICA no será responsable por ningún daño ocasionado por fallas en el funcionamiento de los servicios electrónicos y los servicios de comunicación electrónica, incluyendo el envío de la Oferta de Préstamo y la Aceptación por parte del Usuario Tomador.\n\nDINÁMICA no será responsable por las conductas del Usuario Tomador que se originen o vinculen con información contenida en correos electrónicos falsos o que aparenten provenir de DINÁMICA que sean enviados por terceros sin relación con DINÁMICA; como así tampoco responderán por las consecuencias dañosas de tales conductas, ni por la circulación de los mencionados correos electrónicos falsos.";

String disposicionesGeneralesTituloCGL = "11. Disposiciones Generales";

String aDisposicionesGeneralesCuerpoCGL =
    "11.1. Cesión: el Usuario Tomador no podrá ceder los derechos y/u obligaciones bajo el presente Contrato ni su posición jurídica en el Contrato. Cualquier cesión realizada en violación a esta norma será inválida e inoponible a DINÁMICA. DINÁMICA podrá ceder los derechos y/u obligaciones y/o su posición jurídica en el Contrato sin necesidad de notificar al Usuario Tomador o de obtener su consentimiento. Asimismo, todos los créditos de titularidad de DINÁMICA originados en el Préstamo (y/o en cualquier concepto relacionado con el Préstamo), podrán ser cedidos por DINÁMICA en los términos de los artículos 70 a 72 de la Ley 24.441 (y/o cualquier norma que la complemente o reemplace en el futuro) sin necesidad de notificación alguna al Usuario Tomador, prestando éste su consentimiento expreso al momento de la Aceptación.\n\n11.2. Validez – ejercicio de derechos: la invalidez de cualquiera de las disposiciones del Contrato no afectará la validez de las restantes ni del Contrato en su conjunto. La falta o demora en el ejercicio por parte de DINÁMICA de cualquier derecho, facultad, privilegio y/o recurso que tenga en virtud del Contrato, no implicará renuncia, ni espera, ni disminución respecto del mismo, ni de ningún otro derecho. Los derechos, facultades y recursos aquí expuestos no excluyen los conferidos por la ley.\n\n11.3. Términos definidos: los términos utilizados en mayúsculas tendrán el significado que se le asigna en los Términos y Condiciones de Uso de DINÁMICA y demás documentos incorporados a ellos.\n\n11.4. Notificaciones: serán válidas todas las notificaciones realizadas al Usuario Tomador por parte de DINÁMICA en:\n     • La dirección de correo electrónico principal registrada por el Usuario Tomador en cualquiera de las Plataformas.\n     • La Cuenta DINÁMICA de titularidad del Usuario Tomador.\n     • A través de aplicaciones de dispositivos móviles de titularidad de DINÁMICA.\n     • A través de mensajes de texto, al número de celular registrado por el Usuario Tomador en las Plataformas.\n\n11.5. Aplicación de los Términos y Condiciones de DINÁMICA: a todos los efectos que pudieran corresponder, serán de aplicación los ";

String bDisposicionesGeneralesCuerpoCGL = "Términos y Condiciones de Uso";

String cDisposicionesGeneralesCuerpoCGL =
    " de DINÁMICA y demás documentos incorporados a ellos, los cuales se facilitan al Usuario Tomador a través de los enlaces al sitio correspondiente provistos en caracteres destacados. La aceptación del Préstamo implica la conformidad de esta circunstancia por parte del Usuario Tomador.\n\n11.6. Ausencia de conexidad contractual: a todo evento se establece expresamente que no existe conexidad alguna entre el contrato correspondiente al Préstamo y aquél correspondiente al Sistema de Gestión de Pagos de DINÁMICA.\n\n11.7. Costos impositivos: cualquier tasa, contribución o impuesto que graven el Préstamo serán por cuenta del Usuario Tomador. En caso de que el Contrato quedase alcanzado por el impuesto de sellos, el mismo será soportado por el Usuario Tomador, en forma exclusiva.\n\n11.8. Ley aplicable y jurisdicción: el Contrato se regirá por las leyes vigentes en Argentina. La interpretación y/o ejecución del Contrato se someterá a los tribunales ordinarios de la Ciudad de Santiago del Estero, renunciando en forma expresa a la jurisdicción federal y/o cualquier otra jurisdicción que corresponda en virtud de leyes especiales.";
